repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: 🐶 Ruff Linter
        language: system
        types: [python]
        entry: uv run ruff check --fix
        require_serial: true
        stages: [pre-commit, pre-push, manual]
        exclude: ^\.ma-data/

      - id: ruff-format
        name: 🐶 Ruff Formatter
        language: system
        types: [python]
        entry: uv run ruff format
        require_serial: true
        stages: [pre-commit, pre-push, manual]
        exclude: ^\.ma-data/

      - id: check-ast
        name: 🐍 Check Python AST
        language: system
        types: [python]
        entry: uv run check-ast
        exclude: ^\.ma-data/

      - id: check-case-conflict
        name: 🔠 Check for case conflicts
        language: system
        entry: uv run check-case-conflict
        exclude: ^\.ma-data/

      - id: check-docstring-first
        name: ℹ️  Check docstring is first
        language: system
        types: [python]
        entry: uv run check-docstring-first
        exclude: ^\.ma-data/

      - id: check-json
        name: ｛ Check JSON files
        language: system
        types: [json]
        entry: uv run check-json
        files: ^(provider/manifest\.json)|(tests/fixtures/.+\.json)$

      - id: check-merge-conflict
        name: 💥 Check for merge conflicts
        language: system
        types: [text]
        entry: uv run check-merge-conflict
        exclude: ^\.ma-data/

      - id: check-toml
        name: ✅ Check TOML files
        language: system
        types: [toml]
        entry: uv run check-toml

      - id: codespell
        name: ✅ Check code for common misspellings
        language: system
        types: [text]
        entry: uv run codespell
        exclude: ^(\.ma-data/|docs-site/package-lock\.json)

      - id: detect-private-key
        name: 🕵️ Detect Private Keys
        language: system
        types: [text]
        entry: uv run detect-private-key
        exclude: ^\.ma-data/

      - id: end-of-file-fixer
        name: ⮐ Fix End of Files
        language: system
        types: [text]
        entry: uv run end-of-file-fixer
        stages: [pre-commit, pre-push, manual]
        exclude: ^\.ma-data/

      - id: no-commit-to-branch
        name: 🛑 Don't commit to main branch
        language: system
        entry: uv run no-commit-to-branch
        pass_filenames: false
        always_run: true
        args:
          - --branch=main

      - id: trailing-whitespace
        name: ✄ Trim Trailing Whitespace
        language: system
        types: [text]
        entry: uv run trailing-whitespace-fixer
        stages: [pre-commit, pre-push, manual]
        exclude: ^\.ma-data/

      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false
